cargo-features = ["per-package-target"]

[package]
name = "chess-ui"
version = "0.1.0"
edition = "2021"
forced-target = "wasm32-unknown-unknown"

[dependencies]
macroquad = "0.3"

[toolchain]
channel = "nightly"
